"""update_vector_dim_to_768

Revision ID: dd1c7c74d841
Revises: c1e9f4a7b2d0
Create Date: 2026-09-09 18:50:44.689529
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



revision: str = 'dd1c7c74d841'
down_revision: Union[str, Sequence[str], None] = 'c1e9f4a7b2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###